name: contract-ci

on:
  push:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes --root backend
        id: build

      - name: Run Forge format check
        run: |
          forge fmt --check --root backend
        id: format

      - name: Run Forge tests
        run: |
          forge test -vvv --root backend
        id: test
